name: Test and Deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches: [ "main" ]
    types: [opened, synchronize, reopened]
  
jobs:
  test_and_deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [22.x]
        
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      
      - run: npm ci
      - run: npm run build --if-present
      - run: npm test
